### ISSUE TITLE
Bug: Some guesses are being accepted but the correct color is not applying.

### ISSUE THREAD

**Issue by moth-dust** [KojinKuro/ludole#20]
In the below screen shot, Super Mario World 2 should be showing up as red instead of grey. Since red is still evaluating for other guesses I believe for whatever reason the first guess is being evaluated as a 0 instead of at least a 1, causing it to not receive a color assignment. I'm am not sure though, as I do not know why this would be happening.
![image](https://github.com/KojinKuro/ludole/assets/155918416/f2014bd6-8b08-4235-8474-eb997e3c6930)
![image](https://github.com/KojinKuro/ludole/assets/155918416/7363d8c0-d619-418b-9bd6-ee1afe063fc4)

This does not happen with the same guess on other games.

![image](https://github.com/KojinKuro/ludole/assets/155918416/e6748f87-822b-4230-b81b-e0766ed45a6f)

**Comment by KojinKuro** [comment]
This is not a bug. It is working as intended. 

If the two games being compared have no similarity, it will give 0/100 points. The guess history displays guesses with 0 points as gray. We can change this by changing how the guess arrays display guesses with 0 points, but the points should not start at 1 because if they have no similarity they should give 0 points.
